import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import fs from "fs";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clark Narvas",
  description: "Generated by create next app",
};

const Header = (
  <nav className="mb-10">
  <div className="header text-center p-5x">
    
    <div className="container mx-auto p-4">
    <Link href="/">
    <h2 className="text-2xl font-bold">Clark Narvas</h2>
    </Link>
    </div>
  </div>

  <div className="flex">
  <div className="mx-auto">
    <div className="flex flex-row space-x-10" >
      <div><a>NOTES</a></div>
      <div ><a>CLARK</a></div>
      <div><a>VIDEOS</a></div>
      <div><a>WORK</a></div>
    </div>
  </div>
  </div>
  </nav>
);

const copyrightDate = new Date().getFullYear();
const Footer = (
  <div className="footer text-center mt-10 p-10 bg-cnbackground">
    <h3 className="brand-font text-5xl mb-3 ">On a new journey</h3>
    <a className="block link" href="mailto:clark@narvas.co.uk" >Let's get in touch - I want to hear about what you're up to</a>
    <span className="opacity-50 mt-2 block" >Copyright Clark Narvas - {copyrightDate}</span><br></br>

  </div>
);





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      {Header}
      <div className="min-h-screen">
        {children}
      </div>
      {Footer}
      </body>
    </html>
  );
}
