import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import fs from "fs";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clark Narvas",
  description: "Generated by create next app",
};

const Header = (
  <div className="header">
    
    <Link href="/">
    <h2 className="text-2xl font-bold">Clark Narvas Blog</h2>
    </Link>
  </div>
);

const Footer = (
  <div className="footer">
    <h2>Clark Narvas Blog</h2>
  </div>
);





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className="container mx-auto">
      {Header}
      {children}
      </div></body>
    </html>
  );
}
